class not_exist_error(Exception):
    pass

class already_exist_error(Exception):
    pass